/* Generated By:JJTree: Do not edit this line. ASTAssignSub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignSub extends SimpleNode {
  public ASTAssignSub(int id) {
    super(id);
  }

  public ASTAssignSub(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a2fe884a63cb70ee24fb3834455429b8 (do not edit this line) */
