/* Generated By:JJTree: Do not edit this line. ASTAssignMult.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignMult extends SimpleNode {
  public ASTAssignMult(int id) {
    super(id);
  }

  public ASTAssignMult(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50329f71fe49979188fbef7de6b05c02 (do not edit this line) */
