/* Generated By:JJTree: Do not edit this line. ASTAssignXOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignXOR extends SimpleNode {
  public ASTAssignXOR(int id) {
    super(id);
  }

  public ASTAssignXOR(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bbf94f6030c4ba99e21466eb0a18fc32 (do not edit this line) */
