/* Generated By:JJTree: Do not edit this line. ASTAssignOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignOr extends SimpleNode {
  public ASTAssignOr(int id) {
    super(id);
  }

  public ASTAssignOr(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c707a742ac7af5ab57a56afd7a783ce9 (do not edit this line) */
