/* Generated By:JJTree: Do not edit this line. ASTAssinShiftLeft.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssinShiftLeft extends SimpleNode {
  public ASTAssinShiftLeft(int id) {
    super(id);
  }

  public ASTAssinShiftLeft(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d993d66962434c27f92135a7c5f2e4f1 (do not edit this line) */
