/* Generated By:JJTree: Do not edit this line. ASTAssinAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssinAnd extends SimpleNode {
  public ASTAssinAnd(int id) {
    super(id);
  }

  public ASTAssinAnd(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3f0e84a0cda0af2d199af482e52f12b (do not edit this line) */
