/* Generated By:JJTree: Do not edit this line. ASTAssignAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignAdd extends SimpleNode {
  public ASTAssignAdd(int id) {
    super(id);
  }

  public ASTAssignAdd(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=01c3e8589c5e4b5a5c504fe86684a22f (do not edit this line) */
