/* Generated By:JJTree: Do not edit this line. ASTAssignRem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignRem extends SimpleNode {
  public ASTAssignRem(int id) {
    super(id);
  }

  public ASTAssignRem(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7a7bc572f00215a031f96cd159a2f4c2 (do not edit this line) */
