/* Generated By:JJTree: Do not edit this line. ASTAssignDiv.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTAssignDiv extends SimpleNode {
  public ASTAssignDiv(int id) {
    super(id);
  }

  public ASTAssignDiv(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=74233a43b615d3b8d88aee8c023202ad (do not edit this line) */
