/* Generated By:JJTree: Do not edit this line. ASTBitOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTBitOR extends SimpleNode {
  public ASTBitOR(int id) {
    super(id);
  }

  public ASTBitOR(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0038a7cb52f29844bc7a8380e04dc910 (do not edit this line) */
