/* Generated By:JJTree: Do not edit this line. ASTBitAND.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTBitAND extends SimpleNode {
  public ASTBitAND(int id) {
    super(id);
  }

  public ASTBitAND(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56341e2cde54a481b934fbc5ac13704f (do not edit this line) */
