/* Generated By:JJTree: Do not edit this line. ASTBitComplement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTBitComplement extends SimpleNode {
  public ASTBitComplement(int id) {
    super(id);
  }

  public ASTBitComplement(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0459e4d04047d02929ef2a9c49a4721 (do not edit this line) */
