/* Generated By:JJTree: Do not edit this line. ASTCast.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTCast extends SimpleNode {
  public ASTCast(int id) {
    super(id);
  }

  public ASTCast(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6cd929e32e4cc1b663cd58fb0e56def4 (do not edit this line) */
