/* Generated By:JJTree: Do not edit this line. ASTCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTCondition extends SimpleNode {
  public ASTCondition(int id) {
    super(id);
  }

  public ASTCondition(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode cond = (SimpleNode)jjtGetChild(0);
	  if (cond instanceof ASTIdentifier)
		  return new StringBuilder("(" + cond.toBSV() + ")");
	  else
		  return new StringBuilder(cond.toBSV());
  }
}
/* JavaCC - OriginalChecksum=d07895571335b72015511e80c36284d1 (do not edit this line) */
