/* Generated By:JJTree: Do not edit this line. ASTDivison.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTDivison extends SimpleNode {
  public ASTDivison(int id) {
    super(id);
  }

  public ASTDivison(C2BSVParser p, int id) {
    super(p, id);
  }
  
  public StringBuilder toBSV() {
	  SimpleNode n0 = (SimpleNode)jjtGetChild(0);
	  SimpleNode n1 = (SimpleNode)jjtGetChild(1);
	  return new StringBuilder("(" + n0.toBSV() + " / " + n1.toBSV() + ")");
  }

}
/* JavaCC - OriginalChecksum=a17202a209ff4f5f3d5a35e4c4639224 (do not edit this line) */
