/* Generated By:JJTree: Do not edit this line. ASTDo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTDo extends SimpleNode {
  public ASTDo(int id) {
    super(id);
  }

  public ASTDo(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=be84e06f7f00f63736e7033db6c6659c (do not edit this line) */
