/* Generated By:JJTree: Do not edit this line. ASTFunctionBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTFunctionBody extends SimpleNode {
  public ASTFunctionBody(int id) {
    super(id);
  }

  public ASTFunctionBody(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0931b0a5d1501e8c863686f75d8db016 (do not edit this line) */
