/* Generated By:JJTree: Do not edit this line. ASTFunctionReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTFunctionReturn extends SimpleNode {
  public ASTFunctionReturn(int id) {
    super(id);
  }

  public ASTFunctionReturn(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbf9a94059f27f5d0cf4c9f24fabc6f2 (do not edit this line) */
