/* Generated By:JJTree: Do not edit this line. ASTFunctionHeader.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTFunctionHeader extends SimpleNode {
  public ASTFunctionHeader(int id) {
    super(id);
  }

  public ASTFunctionHeader(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5ca16244d3ffaa567465363bc87b336 (do not edit this line) */
