/* Generated By:JJTree: Do not edit this line. ASTFunctionDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTFunctionDefinition extends SimpleNode {
  public ASTFunctionDefinition(int id) {
    super(id);
  }

  public ASTFunctionDefinition(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=671869c6ed10eec8df483db19f7b6695 (do not edit this line) */
