/* Generated By:JJTree: Do not edit this line. ASTGreaterOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTGreaterOrEqual extends SimpleNode {
  public ASTGreaterOrEqual(int id) {
    super(id);
  }

  public ASTGreaterOrEqual(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode n0 = (SimpleNode)jjtGetChild(0);
	  SimpleNode n1 = (SimpleNode)jjtGetChild(1);
	  return new StringBuilder("(" + n0.toBSV() + " >= " + n1.toBSV() + ")");
  }
}
/* JavaCC - OriginalChecksum=18c6cd1d0d2b85542db85a08ae488335 (do not edit this line) */
