/* Generated By:JJTree: Do not edit this line. ASTGreater.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTGreater extends SimpleNode {
  public ASTGreater(int id) {
    super(id);
  }

  public ASTGreater(C2BSVParser p, int id) {
    super(p, id);
  }
  
  public StringBuilder toBSV() {
	  SimpleNode n0 = (SimpleNode)jjtGetChild(0);
	  SimpleNode n1 = (SimpleNode)jjtGetChild(1);
	  return new StringBuilder("(" + n0.toBSV() + " > " + n1.toBSV() + ")");
  }

}
/* JavaCC - OriginalChecksum=92e0a1e549452eefb579830cd6520963 (do not edit this line) */
