/* Generated By:JJTree: Do not edit this line. ASTInt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTInt extends SimpleNode {
  public ASTInt(int id) {
    super(id);
  }

  public ASTInt(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  return new StringBuilder(value.toString());
  }
  
}
/* JavaCC - OriginalChecksum=ead57a3cde75dfefd11832e560faafcd (do not edit this line) */
