/* Generated By:JJTree: Do not edit this line. ASTInitializedAs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTInitializedAs extends SimpleNode {
  public ASTInitializedAs(int id) {
    super(id);
  }

  public ASTInitializedAs(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e79985e7189d33a24732f5f365abfab6 (do not edit this line) */
