/* Generated By:JJTree: Do not edit this line. ASTListOfExpressions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTListOfExpressions extends SimpleNode {
  public ASTListOfExpressions(int id) {
    super(id);
  }

  public ASTListOfExpressions(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4153996a6b5b43439e90ab3b07afcd85 (do not edit this line) */
