/* Generated By:JJTree: Do not edit this line. ASTListOfIdentifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTListOfIdentifiers extends SimpleNode {
  public ASTListOfIdentifiers(int id) {
    super(id);
  }

  public ASTListOfIdentifiers(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=266e011ef93b964eb2b7e7813b32dd4d (do not edit this line) */
