/* Generated By:JJTree: Do not edit this line. ASTListOfDeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTListOfDeclarations extends SimpleNode {
  public ASTListOfDeclarations(int id) {
    super(id);
  }

  public ASTListOfDeclarations(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=03ef6320fb66701b81fc00edc651f8c5 (do not edit this line) */
