/* Generated By:JJTree: Do not edit this line. ASTListOfArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTListOfArguments extends SimpleNode {
  public ASTListOfArguments(int id) {
    super(id);
  }

  public ASTListOfArguments(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21f3522096a0c5a00a6a6831451cf59c (do not edit this line) */
