/* Generated By:JJTree: Do not edit this line. ASTMember.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTMember extends SimpleNode {
  public ASTMember(int id) {
    super(id);
  }

  public ASTMember(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ee61d48783be04805fdd37b6e3d69938 (do not edit this line) */
