/* Generated By:JJTree: Do not edit this line. ASTNotEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTNotEqual extends SimpleNode {
  public ASTNotEqual(int id) {
    super(id);
  }

  public ASTNotEqual(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode n0 = (SimpleNode)jjtGetChild(0);
	  SimpleNode n1 = (SimpleNode)jjtGetChild(1);
	  return new StringBuilder("(" + n0.toBSV() + " != " + n1.toBSV() + ")");
  }
}
/* JavaCC - OriginalChecksum=8d9b262ed86336f0970b4aff5ec2773a (do not edit this line) */
