/* Generated By:JJTree: Do not edit this line. ASTNegative.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTNegative extends SimpleNode {
  public ASTNegative(int id) {
    super(id);
  }

  public ASTNegative(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode number = (SimpleNode)jjtGetChild(0);
	  return new StringBuilder("-" + number.toBSV());
  }
  
}
/* JavaCC - OriginalChecksum=ddfde0fd7abce0228ae08aa93415f4a9 (do not edit this line) */
