/* Generated By:JJTree: Do not edit this line. ASTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTOR extends SimpleNode {
  public ASTOR(int id) {
    super(id);
  }

  public ASTOR(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode n0 = (SimpleNode)jjtGetChild(0);
	  SimpleNode n1 = (SimpleNode)jjtGetChild(1);
	  return new StringBuilder("(" + n0.toBSV() + " || " + n1.toBSV() + ")");
  }
}
/* JavaCC - OriginalChecksum=adbe8c053cea4478fe0a0b997ba5d162 (do not edit this line) */
