/* Generated By:JJTree: Do not edit this line. ASTPreDecrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTPreDecrement extends SimpleNode {
  public ASTPreDecrement(int id) {
    super(id);
  }

  public ASTPreDecrement(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5fde264df59d8245ea100353b8dce65 (do not edit this line) */
