/* Generated By:JJTree: Do not edit this line. ASTPositive.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTPositive extends SimpleNode {
  public ASTPositive(int id) {
    super(id);
  }

  public ASTPositive(C2BSVParser p, int id) {
    super(p, id);
  }

  public StringBuilder toBSV() {
	  SimpleNode number = (SimpleNode)jjtGetChild(0);
	  return new StringBuilder("+" + number.toBSV());
  }

}
/* JavaCC - OriginalChecksum=3b94a06ce2d1d4ff6b7fb1c0afb911d4 (do not edit this line) */
