/* Generated By:JJTree: Do not edit this line. ASTPostIncrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTPostIncrement extends SimpleNode {
  public ASTPostIncrement(int id) {
    super(id);
  }

  public ASTPostIncrement(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b66b5ba89725ce2cf04034a1475274b1 (do not edit this line) */
