/* Generated By:JJTree: Do not edit this line. ASTPreIncrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTPreIncrement extends SimpleNode {
  public ASTPreIncrement(int id) {
    super(id);
  }

  public ASTPreIncrement(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b26665174829ed1aa2c89fa03b249a42 (do not edit this line) */
