/* Generated By:JJTree: Do not edit this line. ASTPostDecrement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTPostDecrement extends SimpleNode {
  public ASTPostDecrement(int id) {
    super(id);
  }

  public ASTPostDecrement(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=983708ce33ecfadb3969a71c46bfbf6a (do not edit this line) */
