/* Generated By:JJTree: Do not edit this line. ASTRemainder.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTRemainder extends SimpleNode {
  public ASTRemainder(int id) {
    super(id);
  }

  public ASTRemainder(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c03c42cb4728e8ad6d66867824310a47 (do not edit this line) */
