/* Generated By:JJTree: Do not edit this line. ASTReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTReturn extends SimpleNode {
  public ASTReturn(int id) {
    super(id);
  }

  public ASTReturn(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc162bce628ffa1f08956360650e46de (do not edit this line) */
