/* Generated By:JJTree: Do not edit this line. ASTroot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTroot extends SimpleNode {
  public ASTroot(int id) {
    super(id);
  }

  public ASTroot(C2BSVParser p, int id) {
    super(p, id);
  }
  
  public StringBuilder toBSV() {
	  if (this.jjtGetNumChildren() == 0)
		  return null;
	  
	  StringBuilder s = new StringBuilder();
	  for (Node node: this.children) {
		  s.append(((SimpleNode)node).toBSV() + NEW_LINE);
	  }
	  return s;
  }

}
/* JavaCC - OriginalChecksum=f1a5ff25b71b820efebd3f64a1466b28 (do not edit this line) */
