/* Generated By:JJTree: Do not edit this line. ASTShiftRight.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTShiftRight extends SimpleNode {
  public ASTShiftRight(int id) {
    super(id);
  }

  public ASTShiftRight(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cdcad79753a7b390f46d06d19d252e5d (do not edit this line) */
