/* Generated By:JJTree: Do not edit this line. ASTStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTStatement extends SimpleNode {
  public ASTStatement(int id) {
    super(id);
  }

  public ASTStatement(C2BSVParser p, int id) {
    super(p, id);
  }
  
  public StringBuilder toBSV() {
	  StringBuilder s = new StringBuilder();
	  for (int i=0; i<jjtGetNumChildren(); i++) {
		  SimpleNode statement = (SimpleNode)jjtGetChild(i);
		  if (jjtGetNumChildren() == (i+1)) 	// just to avoid NEW_LINE in the last statement
			  s.append(statement.toBSV());
		  else
			  s.append(statement.toBSV() + NEW_LINE);
	  }
	  return s;
  }

}
/* JavaCC - OriginalChecksum=b4460d3fae29b695617d2d4a8d7090f7 (do not edit this line) */
