/* Generated By:JJTree: Do not edit this line. ASTStructsList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTStructsList extends SimpleNode {
  public ASTStructsList(int id) {
    super(id);
  }

  public ASTStructsList(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=753e6b7c8cf023b8e0dc9f0809335a73 (do not edit this line) */
