/* Generated By:JJTree: Do not edit this line. ASTShiftLeft.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTShiftLeft extends SimpleNode {
  public ASTShiftLeft(int id) {
    super(id);
  }

  public ASTShiftLeft(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5d0138a573f1376f627357d32233d07 (do not edit this line) */
