/* Generated By:JJTree: Do not edit this line. ASTStructBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTStructBody extends SimpleNode {
  public ASTStructBody(int id) {
    super(id);
  }

  public ASTStructBody(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d79f06896f52139d667fbdbf255c4db (do not edit this line) */
