/* Generated By:JJTree: Do not edit this line. ASTStructName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTStructName extends SimpleNode {
  public ASTStructName(int id) {
    super(id);
  }

  public ASTStructName(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6f0ed0fc10a6e9bf82c2aaf8a2dcbbe (do not edit this line) */
