/* Generated By:JJTree: Do not edit this line. ASTStructMember.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTStructMember extends SimpleNode {
  public ASTStructMember(int id) {
    super(id);
  }

  public ASTStructMember(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8813eac690d423ea63deaecc630ad226 (do not edit this line) */
