/* Generated By:JJTree: Do not edit this line. ASTXOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lcr.c2bsv.parser;

public
class ASTXOR extends SimpleNode {
  public ASTXOR(int id) {
    super(id);
  }

  public ASTXOR(C2BSVParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2ad8d90982651f57884bbff039d3e6a (do not edit this line) */
