/* Generated By:JavaCC: Do not edit this line. C2BSVParserTreeConstants.java Version 5.0 */
package lcr.c2bsv.parser;

public interface C2BSVParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTFUNCTIONDEFINITION = 2;
  public int JJTFUNCTIONRETURN = 3;
  public int JJTFUNCTIONHEADER = 4;
  public int JJTFUNCTIONBODY = 5;
  public int JJTDECLARATION = 6;
  public int JJTTYPE = 7;
  public int JJTSTRUCTNAME = 8;
  public int JJTSTRUCTBODY = 9;
  public int JJTLISTOFDECLARATIONS = 10;
  public int JJTINITIALIZEDAS = 11;
  public int JJTSTRUCTSLIST = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTARRAY = 14;
  public int JJTLISTOFARGUMENTS = 15;
  public int JJTPARAMETER = 16;
  public int JJTLISTOFIDENTIFIERS = 17;
  public int JJTSTATEMENT = 18;
  public int JJTIF = 19;
  public int JJTCONDITION = 20;
  public int JJTTHEN = 21;
  public int JJTELSE = 22;
  public int JJTWHILE = 23;
  public int JJTDO = 24;
  public int JJTRETURN = 25;
  public int JJTLISTOFEXPRESSIONS = 26;
  public int JJTASSIGNEQUAL = 27;
  public int JJTASSIGNMULT = 28;
  public int JJTASSIGNDIV = 29;
  public int JJTASSIGNREM = 30;
  public int JJTASSIGNADD = 31;
  public int JJTASSIGNSUB = 32;
  public int JJTASSINSHIFTLEFT = 33;
  public int JJTASSINSHIFTRIGHT = 34;
  public int JJTASSINAND = 35;
  public int JJTASSIGNXOR = 36;
  public int JJTASSIGNOR = 37;
  public int JJTCONDITIONALEXPRESSION = 38;
  public int JJTOR = 39;
  public int JJTAND = 40;
  public int JJTBITOR = 41;
  public int JJTXOR = 42;
  public int JJTBITAND = 43;
  public int JJTEQUAL = 44;
  public int JJTNOTEQUAL = 45;
  public int JJTLESS = 46;
  public int JJTGREATER = 47;
  public int JJTLESSOREQUAL = 48;
  public int JJTGREATEROREQUAL = 49;
  public int JJTSHIFTLEFT = 50;
  public int JJTSHIFTRIGHT = 51;
  public int JJTADDITION = 52;
  public int JJTSUBTRACTION = 53;
  public int JJTMULTIPLICATION = 54;
  public int JJTDIVISON = 55;
  public int JJTREMAINDER = 56;
  public int JJTCAST = 57;
  public int JJTPREINCREMENT = 58;
  public int JJTPREDECREMENT = 59;
  public int JJTUNARYEXPRESSION = 60;
  public int JJTPOSITIVE = 61;
  public int JJTNEGATIVE = 62;
  public int JJTBITCOMPLEMENT = 63;
  public int JJTNOT = 64;
  public int JJTPOSITION = 65;
  public int JJTARRAYACCESS = 66;
  public int JJTARGUMENTS = 67;
  public int JJTFUNCTIONCALL = 68;
  public int JJTSTRUCTMEMBER = 69;
  public int JJTPOSTINCREMENT = 70;
  public int JJTPOSTDECREMENT = 71;
  public int JJTMEMBER = 72;
  public int JJTINT = 73;
  public int JJTFLOAT = 74;
  public int JJTSTRING = 75;


  public String[] jjtNodeName = {
    "root",
    "void",
    "FunctionDefinition",
    "FunctionReturn",
    "FunctionHeader",
    "FunctionBody",
    "Declaration",
    "Type",
    "StructName",
    "StructBody",
    "ListOfDeclarations",
    "InitializedAs",
    "StructsList",
    "Identifier",
    "Array",
    "ListOfArguments",
    "Parameter",
    "ListOfIdentifiers",
    "Statement",
    "If",
    "Condition",
    "Then",
    "Else",
    "While",
    "Do",
    "Return",
    "ListOfExpressions",
    "AssignEqual",
    "AssignMult",
    "AssignDiv",
    "AssignRem",
    "AssignAdd",
    "AssignSub",
    "AssinShiftLeft",
    "AssinShiftRight",
    "AssinAnd",
    "AssignXOR",
    "AssignOr",
    "ConditionalExpression",
    "OR",
    "AND",
    "BitOR",
    "XOR",
    "BitAND",
    "Equal",
    "NotEqual",
    "Less",
    "Greater",
    "LessOrEqual",
    "GreaterOrEqual",
    "ShiftLeft",
    "ShiftRight",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Divison",
    "Remainder",
    "Cast",
    "PreIncrement",
    "PreDecrement",
    "UnaryExpression",
    "Positive",
    "Negative",
    "BitComplement",
    "Not",
    "Position",
    "ArrayAccess",
    "Arguments",
    "FunctionCall",
    "StructMember",
    "PostIncrement",
    "PostDecrement",
    "Member",
    "Int",
    "Float",
    "String",
  };
}
/* JavaCC - OriginalChecksum=f7535337c49f91a97b72ca2c7bbce7a5 (do not edit this line) */
